Py4web: 1.20210119.1 on Python 3.9.5 (default, Jun  4 2021, 12:28:51)
[GCC 7.5.0]


Dashboard is at: http://127.0.0.1:8000/_dashboard
[X] loaded _scaffold
[X] loaded examples
[X] loaded xtodo
[X] loaded todo
[X] loaded _websocket
[X] loaded _dashboard
[X] loaded myfeed
[X] loaded _minimal
[X] loaded _default
[ ] loading volt ...
Traceback (most recent call last):
  File "/home/w3p/set4/tmp/py4web/py4web/core.py", line 1062, in import_app
    module = importlib.machinery.SourceFileLoader(
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "apps/volt/__init__.py", line 10, in <module>
    from . import controllers
  File "/home/w3p/set4/tmp/py4web/apps/volt/controllers.py", line 541, in <module>
    from .images_utils import ima_grid
  File "/home/w3p/set4/tmp/py4web/apps/volt/images_utils.py", line 46, in <module>
    def some_func():
  File "/home/w3p/set4/tmp/py4web/py4web/core.py", line 797, in __call__
    func = bottle.route(path,  **self.kwargs)(func)
  File "/home/w3p/set4/tmp/py4web/py4web/ombott/ombott.py", line 122, in decorator
    self.add_route(rule, method, callback, name)
  File "/home/w3p/set4/tmp/py4web/py4web/ombott/ombott.py", line 118, in add_route
    self.router.add(rule, method, handler, name)
  File "/home/w3p/set4/tmp/py4web/py4web/ombott/radirouter.py", line 276, in add
    raise RouteBuildError(f'handlers already registred for: {sorted(common_meth)}')
py4web.ombott.radirouter.RouteBuildError: handlers already registred for: ['GET', 'POST']
[FAILED] loading volt
Traceback (most recent call last):
  File "/home/w3p/set4/tmp/py4web/py4web/core.py", line 1062, in import_app
    module = importlib.machinery.SourceFileLoader(
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1034, in load_module
  File "<frozen importlib._bootstrap_external>", line 859, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "apps/volt/__init__.py", line 10, in <module>
    from . import controllers
  File "/home/w3p/set4/tmp/py4web/apps/volt/controllers.py", line 541, in <module>
    from .images_utils import ima_grid
  File "/home/w3p/set4/tmp/py4web/apps/volt/images_utils.py", line 46, in <module>
    def some_func():
  File "/home/w3p/set4/tmp/py4web/py4web/core.py", line 797, in __call__
    func = bottle.route(path,  **self.kwargs)(func)
  File "/home/w3p/set4/tmp/py4web/py4web/ombott/ombott.py", line 122, in decorator
    self.add_route(rule, method, callback, name)
  File "/home/w3p/set4/tmp/py4web/py4web/ombott/ombott.py", line 118, in add_route
    self.router.add(rule, method, handler, name)
  File "/home/w3p/set4/tmp/py4web/py4web/ombott/radirouter.py", line 276, in add
    raise RouteBuildError(f'handlers already registred for: {sorted(common_meth)}')
py4web.ombott.radirouter.RouteBuildError: handlers already registred for: ['GET', 'POST']
[X] loaded _documentation
Ombott v0.0.1 server starting up (using TornadoServer(reloader=False))...
Listening on http://127.0.0.1:8000/
Hit Ctrl-C to quit.

KeyboardInterrupt (ID: 2) has been caught. Cleaning up...

